# Specify version format
version: "1.0"

image:
  - Visual Studio 2017

# to add several platforms to build matrix
platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    - TARGET: mingw

# Scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

install:
  # Create temp dir to collect test outputs
  - md C:\temp

cache:

# project clone directory
clone_folder: C:\projects\test-ci\test-ci

before_build:
  # Use MinGW-w64 in C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - if "%TARGET%"=="mingw" set MINGW_DIR=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - if "%TARGET%"=="mingw" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%TARGET%"=="mingw" set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%
  - dir C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - if "%TARGET%"=="mingw" mingw32-make --version

build_script:
  - echo %PATH%
  - md C:\projects\test-ci\build
  - cd C:\projects\test-ci\build
  # mingw case
  - if "%TARGET%"=="mingw" cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%configuration% ..\test-ci
  - if "%TARGET%"=="mingw" cmake --build . --config %configuration% -- -j2
  - if "%TARGET%"=="mingw" dir C:\projects\test-ci\build
  - if "%TARGET%"=="mingw" ctest --output-on-failure -V
