# Specify version format
version: "{build}"

image:
  - Visual Studio 2017

# to add several platforms to build matrix
platform:
  - x64

configuration:
  - Release

environment:
  matrix:
    - TARGET: mingw
    - TARGET= msvc15
    - TARGET= uwp-msvc15

# Scripts that are called at very beginning, before repo cloning
init:
  - cmake --version
  - msbuild /version

install:

cache:

# project clone directory
clone_folder: C:\projects\test-ci\test-ci

before_build:
  # Use MinGW-w64 in C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - if "%TARGET%"=="mingw" set MINGW_DIR=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64
  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - if "%TARGET%"=="mingw" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "%TARGET%"=="mingw" set PATH=C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin;%PATH%
  - dir C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin
  - if "%TARGET%"=="mingw" mingw32-make --version

build_script:
  - echo %PATH%
  - md C:\projects\test-ci\build
  - cd C:\projects\test-ci\build
  # mingw case
  - if "%TARGET%"=="mingw" cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%configuration% ..\test-ci
  - if "%TARGET%"=="mingw" cmake --build . --config %configuration% -- -j2
  - if "%TARGET%"=="mingw" dir C:\projects\test-ci\build
  - if "%TARGET%"=="mingw" ctest --output-on-failure

  # msvc15 case
  - if "%TARGET%"=="msvc15" cmake -G "Visual Studio 15 2017" -A "x64" ..\test-ci
  - if "%TARGET%"=="msvc15" cmake --build . --config %configuration% -- /m:2
  - if "%TARGET%"=="msvc15" dir C:\projects\test-ci\build
  - if "%TARGET%"=="msvc15" ctest --output-on-failure

  # uwp-msvc15 case
  - if "%TARGET%"=="uwp-msvc15" cmake -G "Visual Studio 15 2017" -A "x64" -DCMAKE_SYSTEM_NAME:%SYSTEM_NAME% -DCMAKE_SYSTEM_VERSION:%SYSTEM_VERSION% -DBUILD_DEMOS=OFF -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_TUTORIALS=OFF ..\test-ci
  - if "%TARGET%"=="uwp-msvc15" cmake --build . --config %configuration% -- /m:2
  - if "%TARGET%"=="uwp-msvc15" dir C:\projects\test-ci\build

